name: Run pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run custom installer
        run: python3 installer.py
      - name: Run pytest
        run: pytest